### PR TITLE
Backmerge master into UIACom branch

### PR DESCRIPTION
**Pull request by Roemer**

### CODE REVIEW

**Comment by dpisanu** [comment]
so once this is on the branch I will create my PRs for Keyboard and mouse and whatever else I have lined up

**Comment by Roemer** [comment]
Not as easy as it seems. I manually merged UIItem, Mouse and CoreAppXmlConfiguration. I hope I didn't discard anything from the UIACom branch.

**Comment by dpisanu** [comment]
Does the UIACom branch compile for you ?

**Comment by Roemer** [comment]
Yes (with the silverlight applications unloaded, don't have that installed here)

**Comment by Roemer** [comment]
I think this pull request will never be needed since the uiacom branch will superseede the current master.

**Comment by dpisanu** [comment]
ok. then we can maybe get it out to have a clean slate. 
let me get an update from UIACom Branch and see that i get working on that.
Struggling with the GitHub Desktop client at the moment

**Comment by Roemer** [comment]
> Struggling with the GitHub Desktop client at the moment

That's why I switched to SourceTree and the Terminal ;)

**Pull request merged**
