### PR TITLE
Fixed the DataGrid.Winforms ControlTests.

### PR DESCRIPTION
**Pull request by maxinfet**
Changed some control types so we would get the correct automationpeers
back.

### CODE REVIEW

**Comment by Roemer** [comment]
Which tests does this fix? If none, can you create a test to verify this?

**Comment by maxinfet** [comment]
The first test to fail without this change is the SelectRowNotVisibleInitially. The test attempts to scroll but is trying to find a pane instead of a scrollbar. In previous versions of windows the scroll bar must have been a pane but in Windows 8 and 10 it can not find the pane. I dont understand how the table cells could have ever worked but replacing that causes the grid to be able to find cells again for the FindAllTest and the GetRow tests.

**Comment by Roemer** [comment]
But those tests currently all work on windows 10?

**Comment by maxinfet** [comment]
Yeah in Windows 8 and 10 my changes cause this test to pass, because it is able to find the scroll bar. I dont have windows 7 to confirm whether this change is platform specific or UIAComWrapper specific.

**Comment by ivan-danilov** [comment]
Checked. `TableTests`: before the merge 4 tests failing, after merge only 2 (Win7). Only executed on WinForms.

**Pull request merged**
