### PR TITLE
Migration to NUnit

### PR DESCRIPTION
**Pull request by Roemer**
There we go. The migration to NUnit is done. CI (AppVeyor) is up and running.
I think what should be reviewed before merging is the stuff which is not in and test-assembly.
I'll wait a few days max until I merge this to master if I don't get any feedback.

### CODE REVIEW

**Comment by Roemer** [comment]
You might need to look at the patch file (https://github.com/TestStack/White/pull/348.patch) because it's too big.

**Comment by ilya-murzinov** [comment]
I don't have any time to review this, but I want to thank you all for supporting the project! :+1:

**Comment by Roemer** [comment]
Here's a quick summary of non-unittest changes:
* Cleaned some unused files
* Changed nuget to the newer automatic package restore
* AppVeyor integration
* Renamed file CoreConfiguration.cs to ICoreConfiguration.cs
* Changed interface UIItemIdConfiguration to IUIItemIdConfiguration
* Added some german default values to UIItemIdAppXmlConfiguration.cs
* Added 3 new Values to IUIItemIdConfiguration
  * BrowseText
  * OpenFileDialogTitle
  * PropertyGridMiscText
If we're good with those changes, I can merge the pull request.

**Comment by Roemer** [comment]
Why did you delete it?

**Comment by maxinfet** [comment]
I didnt meen to close thI did not mean tp close and delete this. Sorry.

**Comment by Roemer** [comment]
Thought so ;-) I' ll merge in a few hours.

**Pull request merged**
