### PR TITLE
Added IsSelected Property to ListViewCell

### PR DESCRIPTION
**Pull request by maxinfet**
Added the ability to get whether a ListViewCell is focused independent
of the Text, Combobox or Checkbox that the ListViewCell contains. This
required me to change the search criteria in ListViewRow and in
ListViewCellFactory so I could get a list of DataGridItems then get
their children when creating the ListViewCell. I also had to store a seperate cell automationelement on the ListViewCell and then pass the child control down through the base.

### CODE REVIEW

**Comment by maxinfet** [comment]
This pull request relates to this issue https://github.com/TestStack/White/issues/353

**Comment by maxinfet** [comment]
Also I should note I tried going the rout of using the selection item pattern but DataGridItems don't support the selection item pattern.

**Comment by Roemer** [comment]
> Also I should note I tried going the rout of using the selection item pattern but DataGridItems don't support the selection item pattern.

Can you add this as comment in the code?

**Comment by maxinfet** [comment]
Sure thing.

**Comment by maxinfet** [comment]
Apparently I didnt run all the datagrid test. I will figure out what is going on with these tests that failed.

**Comment by Roemer** [comment]
:-)

**Comment by maxinfet** [comment]
So after looking at this closer ListView being used for DataGrid seems really wrong. I can't make the changes I want to make because it breaks how a normal ListView functions. I am actually going to write a datagrid control to handle the datagrid so that I dont need to introduce aton of special cases to the ListViewCode. I will be reverting these changes.

**Pull request closed without merging**
