### PR TITLE
Deleted unused files, renamed some interfaces to begin with an "I"

### PR DESCRIPTION
**Pull request by Roemer**

### CODE REVIEW

**Comment by Roemer** [comment]
Just some random cleanups. Should not lead to any problems.

**Comment by JakeGinnivan** [comment]
This introduces rather major public API breaking changes. I suggest writing up a migration guide to go with the release and highlight it in the release, ideally not make the breaking change at all though

**Comment by Roemer** [comment]
I think pretty much all the renamed interfaces are mainly used by White itself and probably never by someone else. We could think about making some of those internal. Or do you see any specific ones which were used by "consumers" of White?

**Comment by Roemer** [comment]
I added the interface renames to the changelog.

**Comment by dpisanu** [comment]
I really dislike when suddenly APIs change namewise breaking the functionality.
I find a graceperiod change alot more integration friendly. Going side by side for a certain time where the old is marked as Deprecated.
Visual Studio then will Warn on this without breaking integration completely.

I wrote a complete wrapper around White for my project and am directly using alot of the Interfaces in my code. So I would not go so far as to presume that most of the stuff is internal and nobody uses it.

The changes in this Pull are mild at best. I think they shouldn't cause such a big headache.

**Comment by JakeGinnivan** [comment]
> I think pretty much all the renamed interfaces are mainly used by White itself and probably never by someone else. We could think about making some of those internal. Or do you see any specific ones which were used by "consumers" of White?

As @dpisanu said, when I was using white last I had wrappers around white and other extensions which used the interfaces directly. This is a library used by many people in a lot of different companies, possibly breaking them for no benefit is not great.

**Comment by dpisanu** [comment]
I can only speak for my motivation driving rename changes for Interfaces.

I try to go by some if the most used naming patterns/schemes.

https://msdn.microsoft.com/en-us/library/ms229040(v=vs.110).aspx

In White the naming is inconsistent in that regard.
So a rename to adhere to things like a leading "I" on interace names is in my opinion good.

Not sure how everybody else works and what coding guidelines they use but I am running a strict ship in that regards with constant Re-Sharper auto formatting and Sonar Analysis in regards to Code Documentation + Code Styling debt.

**Comment by Roemer** [comment]
I'd go with @dpisanu. And since development on White starts rolling again I think having a clean and clear codebase motivates more people to jump in. As long as breaking changes are documented I don't see a big deal, especially if it's only renaming something.

**Comment by JakeGinnivan** [comment]
White was written in .NET 1.1, these guidelines were not as strong then. This change is one I considered ages ago and decided *not* to make the breaking changes at that time.

> I think having a clean and clear codebase motivates more people to jump in
Agreed, but unneeded breaking changes are annoying to consumers

My thoughts on API changes, especially breaking ones was to have the UIA Com Wrapper branch be the v1 release of White. At that point make all breaking changes in one go and rev the major version and from that point adhere to SemVer.

**Comment by JakeGinnivan** [comment]
Don't get me wrong, I am *super* happy to see activity on White :)

**Comment by dpisanu** [comment]
If I recall Microsoft already had such a guideline for 1.1
https://msdn.microsoft.com/en-us/library/8bc1fexb(v=vs.71).aspx
:-p

Breaking is never fun it happens from time to time.
I think after a few years now is the time to let some of the nitpick points me upstreamed :)

**Comment by JakeGinnivan** [comment]
Well thoughtworks may not have been following the guidelines at that point, I am not sure, I did not write this project.

I am just trying to understand what value renaming the interfaces brings that is worth a breaking change?

**Pull request merged**
