### PR TITLE
[WIP] UIA Com Wrapper

### PR DESCRIPTION
**Pull request by JakeGinnivan**

### CODE REVIEW

**Comment by AndyStewart** [comment]
Hi

I was considering doing this myself as the project I'm currently working on could do with it being upgraded to the latest UIA wrapper, is there any reason why this hasn't been merged in or is there anything I can do to help this happen?

Thanks

Andy

**Comment by JakeGinnivan** [comment]
Hey,

The problem is the control lookup dictionary falls short of getting this branch fully functional and I am not doing anything in this area at the moment to keep it pushing forward. There are a bunch of failing tests, I think we need to rethink the core to get it over the line.
Happy to help plan roadmap and such but need someone/someones to do the work as I have too much above this on the list :(

Sent from my Windows Phone
________________________________

**Comment by maxinfet** [comment]
I am currently looking into the control dictionary just haven't had a lot of time to work on it. I have a couple pull request to fix failing test in this branch as well.

**Comment by JakeGinnivan** [comment]
I have a month off starting next week, I hope to at least triage all issues, merge prs and come up with a plan on where to go next before the month is done.

Sent from my Windows Phone
________________________________

**Comment by maxinfet** [comment]
I will get together the solution I was looking into for the control dictionary for next week then.

**Comment by JakeGinnivan** [comment]
:) feel free to ping me if you want to bounce ideas!

Sent from my Windows Phone
________________________________

**Pull request merged**
