### PR TITLE
Added Detach() to Application so you can prevent it from closing after the test finished

### PR DESCRIPTION
**Pull request by Roemer**
This allows to keep the application open and continue with another test or whatever.

### CODE REVIEW

**Comment by dpisanu** [comment]
Please merge this in.
With an Attach a Detach makes completely sense.
This saves everybody quite the headache I think.
From personal experience I can say "I am fed up having to always do special tricks on Dispose just so that Test Stack doesn't kill my app between Test Stubs in one Suite".

**Comment by Roemer** [comment]
I don't completely like it yet. Also the Window needs a property to be kept open on dispose. I'll adjust this here soon.

**Comment by dpisanu** [comment]
ah. the blasted window. true. it's not only the Application that has been somewhat of a pain but it's also the dispose on the window.

**Comment by Roemer** [comment]
Added the changes. What do you guys think? Can we merge this PR?

**Comment by dpisanu** [comment]
Ideally would be a Detach on the Application, and that signals all it's Windows to skip the Dispose.
Because now you will need to set this Property on the Application AND all the corresponding Windows.

As a first step I would say this is ok, but should not be the final one.

e.g.: What happens when you KeepOpenOnDispose = false for the Application but KeepOpenOnDispose = true for the Window.
What is the effect? Is the Window still removed because the Application is being Disposed or is the Disposing of the Application aborted?

**Comment by JakeGinnivan** [comment]
We could put this setting on `CoreAppXmlConfiguration` instead which is in line with existing settings?

**Comment by dpisanu** [comment]
I second that proposal of putting it in **CoreAppXmlConfiguration**.
It doesn't get appreciated enough.

**Comment by Roemer** [comment]
I like putting it in CoreAppXmlConfiguration, I just did with the newest commit. Will merge this later.

**Pull request merged**
