### PR TITLE
Extending Extention Methods for WPFUiItem

### PR DESCRIPTION
**Pull request by dpisanu**
Extending and Documenting the Extention Methods for IUIItem in the WPFUIItem class.

Extended the IUIItemContainer Interface:
- Added Exists Methods
- Added further GetMultiple Methods
- Added Documentation

Extended the UIItemContainer Class
- Implementing the new methods defined in the Interface
- Code Documentaton
- Put in some Regions to declutter the Code abit

Extended the WPFUIItem Extention Methods Class
- Added Regions
- Added Documentation
- Changed the where Constraint from UIItem to IUIItem
- Added some more GetMultiple Methods

### CODE REVIEW

**Comment by Roemer** [comment]
Why are you indentimg the text in the summary? Never seen this convention, also all other comments in White are not indented afaik.

**Comment by dpisanu** [comment]
Those are my re-sharper settings at work there.
Besides the indenting inconsistency though. Is the change ok?
I see the AppVeyor Checks were failing as of yesterday already.

**Comment by Roemer** [comment]
Would be cool if you use different settings for the White Solution. I'm still reviewing. Yes, the build error is since yesterday, I'll have a look at it later.

**Comment by dpisanu** [comment]
No Problem regarding the settings.
Maybe we can settle on some Resharper Settings for White that anybody can use

**Comment by Roemer** [comment]
I like the change, the code looks cleaner now. Only three things I'd like to see different (all are probably your resharper settings):
- Remove the indent in the summary
- Use var
- Do not remove the "private" Keyword

Can you create a new changeset with those adjustments?
And I agree, having a resharper settings file somewhere is a nice idea.

**Comment by dpisanu** [comment]
lets see where i removed the private keyword.
I'll get on the indenting, no issue.

**Comment by Roemer** [comment]
Oh and some new GetMultiple Methods are not virtual, you should add that as well.

**Comment by Roemer** [comment]
Looks good to me now. No idea why other builds failed to be honest.

**Pull request merged**
