### PR TITLE
Fixed DatePicker test for winforms.

### PR DESCRIPTION
**Pull request by maxinfet**
Added LegacyIAccessiblePattern to get date value from date picker.

### CODE REVIEW

**Comment by Roemer** [comment]
Which test is broken? Only on certain systems? What is the legacyiaccessiblepattern exactly?

**Comment by maxinfet** [comment]
I wasn't able to confirm that this was working on any windows version before Windows 8 (I don't have one to test against) but on my Windows 8 and 10 machines when I attempted to get the date pickers value from the value pattern it wasn't returning anything but the LegacyIAccessiblePattern was returning the value so I added it as a fall back. I will remove the fix and document which specific test breaks without this change. It would also be good if some one with a Windows 7 or older machine could tell me whether this is passing or failing in the UIAComWrapper branch.

**Comment by maxinfet** [comment]
I removed the fix to validate which test were affected by this change. The GetDate in DatePickerTests will return null if we just use the value pattern. I confirmed this on Windows 8 when I made this fix and just now on Windows 10.

**Comment by Roemer** [comment]
I do not have the LegacyIAccessiblePattern available. is it only on the com wrapper?

**Comment by maxinfet** [comment]
When using inspect that pattern is available on almost all controls.

**Comment by ivan-danilov** [comment]
Checked on Win7, seems to work. At least failing tests are really fixed :+1:

**Pull request merged**
