### PR TITLE
Update GetMultipleTest.cs to use nunit

### PR DESCRIPTION
**Pull request by maxinfet**
- Renamed GetMultipleTest.cs to GetMultipleTests.cs
- Added assert for exceptions that Roemer suggested
- Added assert for count Roemer suggested and changed the array of UIItems to a list so they have a count property

### CODE REVIEW

**Comment by maxinfet** [comment]
Sorry, the original change and the changes you suggest are now in this pull request. I think this pull request was created because I blew away my fork of White because of some changes I had in it and got a new fork.

**Comment by Roemer** [comment]
Here's some feedback:
1. Somehow there's a jxqlbjkt.vrx.txt textmessage (edited commit message), we don't want that.
2. Delete the GetMultipleTest.cs file

**Comment by Roemer** [comment]
I just copied /pasted your adjusted file :)

**Comment by maxinfet** [comment]
Thank you, sorry for the hassle. How do I edit a commits text? I used this solution https://help.github.com/articles/changing-a-commit-message/ . That's what that strange jxqlbjkt.vrx.txt file was.

**Pull request closed without merging**
