### PR TITLE
Updating to allow to search over an element without a frameworkId

### PR DESCRIPTION
**Pull request by omireault**
Feedback appreciated.

### CODE REVIEW

**Comment by chrisf** [comment]
This helped fix my issue when trying to access the nodes on a tree view. Thanks!

**Comment by AustinMatherne** [comment]
@chrisf can you share how you accessed the tree nodes? I'm working around the same issue right now.

**Comment by AustinMatherne** [comment]
This resolves #277.

**Comment by omireault** [comment]
@AustinMatherne Is there a status update for this? I am kinda new to the Git stuff, but I don't think this is been merged.

**Comment by AustinMatherne** [comment]
It hasn't. The PR contains some stuff (mouse up down functions) outside the original scope which should be reverted before merging.

**Comment by omireault** [comment]
Hmm, sorry, as I said, new to git. I thought the PR would only include the
commit I specified.

I will revert those changes and submit a new request for them.

**Pull request closed without merging**
